export { useCourses } from './useCourses'
//export { addUrlsToModule } from './useAddUrlsToModule'
export { useAddCourse } from './useAddCourse'
export { useLogin } from './useLogin'
export { useRegister } from './useRegister'
export { logout } from './useLogout'
export { getModules } from './useGetModules'
export { useUserDetails } from './useUserDetails'
export { useCreateModule } from './useCreateModule'
export { usePutModule } from './usePutModule'
export { useDeleteModule } from './useDeleteModule'
export { useGetVideos } from './useGetVideos'
export { useDeleteVideo } from './useDeleteVideo'

export { useCoursesDetails } from './useCoursesDetails'
export { useAssignCourse } from './useAssignCourse'