export { useLogin } from './useLogin'
export { useRegister } from './useRegister'
export { useHotels } from './useHotels'
export { useHotelsDetails } from './useHotelsDetails'
export { useReserveRoom } from './useReserveRoom'