export * from './validateEmail'
export * from './validatePassword'
export * from './validateConfirPassword'
export * from './validateUsername'
export * from './validateIma'
export * from './validateTitulo'
export * from './validateDescription'
export * from './validateCodigo'